# Import NumPy module

In [1]:
# Once NumPy is installed on your distribution, to import the NumPy module within your Python session
import numpy as np

# ndarray object

In [2]:
a = [1,2,3]
type(a)

list

In [3]:
a = np.array([1, 2, 3])
type(a)

numpy.ndarray

In [4]:
a

array([1, 2, 3])

# ndarray characteristics

In [5]:
a.dtype

dtype('int64')

In [6]:
a.ndim

1

In [7]:
a.shape

(3,)

In [8]:
a.size

3

In [9]:
b = np.array([[1.3, 2.4],[0.3, 4.1]])
print('type = ', b.dtype)
print('number of dimensions = ', b.ndim)
print('shape = ', b.shape)
print('size = ', b.size)

type =  float64
number of dimensions =  2
shape =  (2, 2)
size =  4


In [10]:
b

array([[1.3, 2.4],
       [0.3, 4.1]])

In [11]:
print(b.itemsize) #It defines the size in bytes of each item in the array
print(b.data)

8


In [12]:
len(a) # length

3

In [13]:
a1D = np.array([1, 2, 3, 4])
a1D.shape

(4,)

In [14]:
a2D = np.array([[1, 2], [3, 4]])
a2D.shape

(2, 2)

In [15]:
a3D = np.array([[[1, 2], [3, 4]],[[5, 6], [7, 8]]])
a3D
a3D.shape

(2, 2, 2)

# Types of Data

In [16]:
# For example, data type >> string
g = np.array([['a', 'b'],['c', 'd']])
g

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [17]:
print(g.dtype)
print(g.dtype.name)

<U1
str32


In [18]:
# if you want to define an array with complex values, you can use the dtype option as follows:
f = np.array([[1, 2, 3],[4, 5, 6]], dtype=complex)
f

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [19]:
n = np.array([['1', '2'],['3', '4']])
n.astype(int) # Convert an array to a different type

array([[1, 2],
       [3, 4]])

# Create an Array

## First: Converting Python sequences to NumPy Arrays

In [20]:
# pass a list to the array() function
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [21]:
# pass a sequence of lists to the array() function
b = np.array([[1, 2, 3],[4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
# tuples
c = np.array((1, 2, 3))
c

array([1, 2, 3])

In [23]:
# sequences of tuples.
d = np.array(((1, 2, 3),(4, 5, 6)))
d

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
# sequences of tuples and interconnected lists 
e = np.array([(1, 2, 3), [4, 5, 6], (7, 8, 9)])
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Second: Intrinsic Creation of an Array

In [25]:
# The NumPy library provides a set of functions that generate ndarrays with initial content
# The zeros() function, for example, creates a full array of zeros with dimensions defined by the shape argument. 
# For example, to create a two-dimensional array 3x3, you can use:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
# ones() function creates an array full of ones in a very similar way.
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
# arange(start, end) is a function generates NumPy arrays with numerical sequences 
np.arange(0, 10) # generate a sequence of values between 0 and 10 (end value not include)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [29]:
# generate a sequence of values with precise intervals between them. 
# arange(start, end, gap)
# the gap between one value and the next one in the sequence of values.
np.arange(0, 12, 3) 

array([0, 3, 6, 9])

In [30]:
# gap can also be a float.
np.arange(0, 6, 0.6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

In [31]:
# Another function very similar to arange() is linspace(). 
# arguments (initial value, end value, number of elements)
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### Note: (arange vs. linspace)
- **arange** will not include the end value.
- **linspace** will include the end value.

In [32]:
# random() function will generate an array with many elements as specified in the argument.
np.random.random(3) # The numbers obtained will vary with every run. 

array([0.28918428, 0.13891502, 0.32282197])

In [33]:
# To create a multidimensional array, you simply pass the size of the array as an argument.
np.random.random((3,3))

array([[0.66644481, 0.09149699, 0.15299139],
       [0.71427556, 0.53313493, 0.16349013],
       [0.44385545, 0.48524624, 0.18066088]])

In [34]:
np.random.rand(3,3) # uniform distribution (0 to 1)

array([[0.12536907, 0.56432194, 0.86000214],
       [0.44961716, 0.06618029, 0.60111818],
       [0.36041193, 0.87738646, 0.98535037]])

In [35]:
np.random.randn(4,4) # standard (normal or Gaussian) distribution (center around 0)

array([[-0.02937286, -1.2886179 , -0.40821016,  0.15231715],
       [ 0.68383553, -0.45781761,  0.06502129, -0.83618791],
       [-0.08200177,  0.29964264,  1.10786974, -0.8602703 ],
       [ 0.65558501, -1.37315159, -0.00474706, -0.28316425]])

In [36]:
np.random.randint(2, 10) # 2 inclusive but 10 exclusive

3

In [37]:
np.random.randint(2, size=10) # random 10 integers (from 0 to 1)

array([0, 0, 1, 1, 1, 1, 0, 1, 0, 1])

In [38]:
np.random.randint(5, size=(2, 4)) # random 2*4 array (from 0 to 4)

array([[4, 0, 2, 4],
       [3, 4, 1, 2]])

In [39]:
np.full((2,2),7) #(shape, fill_value)

array([[7, 7],
       [7, 7]])

In [40]:
np.full((4, 4), [1, 2, 3, 4])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [41]:
np.eye(2) # [identity matrix] Return a 2-D array with ones on the diagonal and zeros elsewhere

array([[1., 0.],
       [0., 1.]])

In [42]:
np.empty([2, 2], dtype=int) #(shape, dtype), Return a new array of given shape and type, without initializing entries

array([[4607182418800017408,                   0],
       [                  0, 4607182418800017408]])

# Shape Manipulation

In [43]:
a = np.arange(0, 12) # one-dimensional arrays
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [44]:
# To generate two-dimensional arrays you can use reshape() function. 
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [46]:
# another way by modifying shape attribute
a.shape = (3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
# ravel() function is inverse operation >> convert a two-dimensional array into a one-dimensional array
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [48]:
# inverting the columns with the rows by transpose()
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

# Basic Operations
## 1- Arithmetic Operators

In [49]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [50]:
a+4

array([4, 5, 6, 7])

In [51]:
a*2

array([0, 2, 4, 6])

In [52]:
b = np.arange(4,8)
b

array([4, 5, 6, 7])

In [53]:
a + b # Addition

array([ 4,  6,  8, 10])

In [54]:
np.add(a, b) 

array([ 4,  6,  8, 10])

In [55]:
a - b # Subtraction

array([-4, -4, -4, -4])

In [56]:
np.subtract(a,b)

array([-4, -4, -4, -4])

In [57]:
a * b # Multiplication

array([ 0,  5, 12, 21])

In [58]:
np.multiply(a, b)

array([ 0,  5, 12, 21])

In [59]:
a / b # Division

array([0.        , 0.2       , 0.33333333, 0.42857143])

In [60]:
np.divide(a,b)

array([0.        , 0.2       , 0.33333333, 0.42857143])

## 2-The Matrix Product

In [61]:
A = np.arange(0, 9).reshape(3, 3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [62]:
B = np.ones((3, 3))
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [63]:
A * B

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [64]:
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [65]:
A.dot(B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [66]:
np.dot(B,A)

array([[ 9., 12., 15.],
       [ 9., 12., 15.],
       [ 9., 12., 15.]])

## 3-Increment and Decrement Operators

In [67]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [68]:
a += 1
a

array([1, 2, 3, 4])

In [69]:
a -= 1
a

array([0, 1, 2, 3])

In [70]:
a += 4
a

array([4, 5, 6, 7])

In [71]:
a *= 2
a

array([ 8, 10, 12, 14])

## 4-Universal Functions (ufunc)

In [72]:
a = np.arange(1, 5)
a

array([1, 2, 3, 4])

In [73]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [74]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [75]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [76]:
np.exp(a) # Exponentiation

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

## 5-Aggregate Functions

In [77]:
a = np.array([3.3, 4.5, 1.2, 5.7, 0.3])
a.sum()

15.0

In [78]:
a.min()

0.3

In [79]:
a.max()

5.7

In [80]:
a.argmax() # return the index of maximum number

3

In [81]:
a.mean() #(sum of elements/number of elements) 15/5 = 3

3.0

In [82]:
a.std()

2.0079840636817816

# Indexing, Slicing, and Iterating

## First: Indexing

In [83]:
a = np.arange(10, 16)
a

array([10, 11, 12, 13, 14, 15])

In [84]:
a[4]

14

In [85]:
print(a[-1])
print(a[-6])

15
10


In [86]:
a[[1, 3, 4]] # two square brackets [[]]

array([11, 13, 14])

In [87]:
A = np.arange(10, 19).reshape((3, 3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [88]:
A[1, 2]

15

In [89]:
A[2, 0]

16

In [90]:
A[2][0]

16

In [91]:
A[0]

array([10, 11, 12])

## Second: Slicing

In [92]:
a = np.arange(10, 16)

In [93]:
a

array([10, 11, 12, 13, 14, 15])

In [94]:
a[1:5] #[start index, final index]

array([11, 12, 13, 14])

In [95]:
# skip a specific number of following items, then extract the next and skip again
# third number defines the gap in the sequence of the elements
a[1:5:2]  #[start index, final index, gap]

array([11, 13])

In [96]:
a[1:5:3]

array([11, 14])

In [97]:
# omitting
a[::2] #[start index =0, final index = maximum index, gap = 2]

array([10, 12, 14])

In [98]:
a[::3] #[start index =0, final index = maximum index, gap = 3]

array([10, 13])

In [99]:
a[:5:2] #[start index =0, final index = 5, gap = 2]

array([10, 12, 14])

In [100]:
a[:5:] #[start index =0, final index = 5, gap = 1]

array([10, 11, 12, 13, 14])

In [101]:
# two-dimensional array
A = np.arange(10, 19).reshape((3, 3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [102]:
A[0,:] #[row=0 , column=all]

array([10, 11, 12])

In [103]:
A[:,0] #[row=all , column=0]

array([10, 13, 16])

In [104]:
A[0:2, 0:2]

array([[10, 11],
       [13, 14]])

In [105]:
# not contiguous indexes >> specify an array of indexes.
A[[0,2], 0:2]

array([[10, 11],
       [16, 17]])

## Third: Iterating

### loop in python

In [106]:
for i in a:
    print(i)

10
11
12
13
14
15


In [107]:
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [108]:
# loop in python (two-dimensional array)
for row in A:
    for item in row:
        print(item)

10
11
12
13
14
15
16
17
18


In [109]:
for item in A.flat:
    print(item)

10
11
12
13
14
15
16
17
18


### loop in Numpy

In [110]:
# three arguments: the aggregate function, the axis on which to apply the iteration, and the array
# axis = 0(columns), axis = 1(rows)
np.apply_along_axis(np.mean, axis=0, arr=A)

array([13., 14., 15.])

In [111]:
np.apply_along_axis(np.mean, axis=1, arr=A)

array([11., 14., 17.])

In [112]:
def f2(x):
    return x/2

np.apply_along_axis(f2, axis=1, arr=A)

array([[5. , 5.5, 6. ],
       [6.5, 7. , 7.5],
       [8. , 8.5, 9. ]])

# Conditions and Boolean Arrays

In [113]:
A = np.random.random((4, 4))
A

array([[0.99308717, 0.99359753, 0.6937403 , 0.67201012],
       [0.34330609, 0.03119307, 0.49675342, 0.91325435],
       [0.51716253, 0.1733195 , 0.67414073, 0.95899082],
       [0.10926261, 0.67579307, 0.48269313, 0.38264806]])

In [114]:
# you wanted to select all the values < 0.5
A < 0.5

array([[False, False, False, False],
       [ True,  True,  True, False],
       [False,  True, False, False],
       [ True, False,  True,  True]])

In [115]:
A[A < 0.5]

array([0.34330609, 0.03119307, 0.49675342, 0.1733195 , 0.10926261,
       0.48269313, 0.38264806])

# Array Manipulation

## First: Joining Arrays

In [116]:
A = np.ones((3, 3))
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [117]:
B = np.zeros((3, 3))
B

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [118]:
np.vstack((A, B)) # vertical stacking

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [119]:
np.hstack((A,B)) # horizontal stacking

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [120]:
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c = np.array([6, 7, 8])

In [121]:
# np.column_stack and np.row_stack used with one-dimensional arrays
# which are stacked as columns or rows in order to form a new two-dimensional array.
np.column_stack((a, b, c))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [122]:
np.row_stack((a, b, c))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Second: Splitting Arrays

In [123]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [124]:
[B,C] = np.hsplit(A, 2) #split the array horizontally
B # the 4x4 matrix A will be split into two 2x4 matrices.

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [125]:
C

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [126]:
[B,C] = np.vsplit(A, 2) #split the array vertically
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [127]:
C

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [128]:
# split() function, which allows you to split the array into nonsymmetrical parts.
# arguments(array, indexes, axis=1(columns) and axis=0(rows))
[A1,A2,A3] = np.split(A,[1,3],axis=1)
A1

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [129]:
A2

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [130]:
A3

array([[ 3],
       [ 7],
       [11],
       [15]])

In [131]:
[A1,A2,A3] = np.split(A,[1,3],axis=0)
A1

array([[0, 1, 2, 3]])

In [132]:
A2

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [133]:
A3

array([[12, 13, 14, 15]])

# Copies or Views of Objects

## Views

In [134]:
a = np.array([1, 2, 3, 4])
b = a
b

array([1, 2, 3, 4])

In [135]:
a[2] = 0
print(a)
print(b) 

[1 2 0 4]
[1 2 0 4]


In [136]:
c = a[0:2]
c

array([1, 2])

In [137]:
a[0] = 0
print(a)
print(c)

[0 2 0 4]
[0 2]


## Copies

In [138]:
a = np.array([1, 2, 3, 4])
c = a.copy()
print(a)
print(c)

[1 2 3 4]
[1 2 3 4]


In [139]:
a[0] = 0
print(a)
print(c)

[0 2 3 4]
[1 2 3 4]
